# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "App"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT


template: "template_toolkit"
# engines:
    # template:
        # template_toolkit:
            # WRAPPER: layouts/main.tt

# serializer: "JSON"

# engines:
    # serializer:
        # JSON:
            # allow_blessed:   '1'
            # canonical:       '1'
            # convert_blessed: '1'
            # allow_nonref:    '1'
            # boolean_values:   
                # -0
                # -1
serializer: Mutable
Mutable:
        mapping:
            'text/x-yaml'        : YAML
            'text/html'          : YAML
            'text/x-data-dumper' : Dumper
            'text/x-json'        : JSON
            'application/json'   : JSON

# session engine
#
# Simple: in-memory session store - Dancer2::Session::Simple
# YAML: session stored in YAML files - Dancer2::Session::YAML
#
# Check out metacpan for other session storage options:
# https://metacpan.org/search?q=Dancer2%3A%3ASession&search_type=modules
#
# Default value for 'cookie_name' is 'dancer.session'. If you run multiple
# Dancer apps on the same host then you will need to make sure 'cookie_name'
# is different for each app.
#
#engines:
#  session:
#    Simple:
#      cookie_name: testapp.session
#
#engines:
#  session:
#    YAML:
#      cookie_name: eshop.session
#      is_secure: 1
#      is_http_only: 1
