requires "Dancer2" => "0.208000";

recommends "YAML"             => "0";
recommends "URL::Encode::XS"  => "0";
recommends "CGI::Deurl::XS"   => "0";
recommends "HTTP::Parser::XS" => "0";

on "test" => sub {
    requires "Test::More"            => "0";
    requires "HTTP::Request::Common" => "0";
};


# File::FindLib;
# SQL::Abstract
# DateTime::Format::Flexible
# Template::Plugin::JSON
# Dancer2::Logger::File 